from pydantic import BaseModel, Field
from typing import Any, Optional
from enum import Enum


# ── Chat ──────────────────────────────────────────────────────────────────────

class ChatMessage(BaseModel):
    role: str       # "user" | "assistant"
    content: str


class BookingState(BaseModel):
    """
    Booking context that the frontend tracks and sends back each turn.
    On the first message everything is None / "intake".
    The frontend updates this from the `state` field of each ChatResponse.
    """
    stage: str = "intake"
    # Stages:
    #   intake       → collecting symptoms
    #   routing      → specialty identified
    #   emergency    → red-flag detected (show emergency UI)
    #   slots_shown  → slots presented, waiting for patient to pick
    #   collecting   → collecting patient name/phone
    #   confirmed    → appointment booked ✅
    #   cancelled    → appointment cancelled

    is_emergency: bool = False
    detected_specialty: Optional[str] = None
    preferred_location: Optional[str] = None   # "wattala" | "thalawathugoda"

    selected_slot_id: Optional[str] = None
    selected_slot_datetime: Optional[str] = None
    selected_doctor_id: Optional[str] = None
    selected_doctor_name: Optional[str] = None

    patient_id: Optional[str] = None
    appointment_id: Optional[str] = None


class ChatRequest(BaseModel):
    session_id: str = Field(..., description="UUID for this conversation — generated by frontend")
    message: str    = Field(..., description="Latest message from the patient")
    history: list[ChatMessage] = Field(
        default=[],
        description="Full conversation so far (not including `message`). Frontend maintains this.",
    )
    # Booking state from the previous turn — send back exactly what was returned
    booking_state: BookingState = Field(default_factory=BookingState)


class ChatResponse(BaseModel):
    session_id: str
    reply: str = Field(..., description="Agent reply — display this to the patient")
    state: BookingState = Field(..., description="Updated booking state — store and send back next turn")


# ── Appointments (for dashboard endpoints) ────────────────────────────────────

class AppointmentStatus(str, Enum):
    confirmed  = "confirmed"
    cancelled  = "cancelled"
    completed  = "completed"


class AppointmentOut(BaseModel):
    id:               str
    patient_id:       str
    doctor_id:        str
    slot_id:          str
    status:           AppointmentStatus
    symptoms_summary: Optional[str] = None
    created_at:       str
    # Joined fields
    doctor_name:      Optional[str] = None
    doctor_specialty: Optional[str] = None
    slot_datetime:    Optional[str] = None
    location:         Optional[str] = None


class CancelRequest(BaseModel):
    cancelled_by: str = Field(..., description="'patient' | 'admin' | 'doctor'")


# ── Doctors / Slots (read-only, for dashboard dropdowns) ──────────────────────

class DoctorOut(BaseModel):
    id:        str
    name:      str
    specialty: str
    location:  str
    is_active: bool


class SlotOut(BaseModel):
    id:            str
    doctor_id:     str
    slot_datetime: str
    is_booked:     bool